### ISSUE TITLE
Crear una Issue sense Assignee retorna error 500

### ISSUE THREAD

**Issue by GuillemCastro** [carlotacb/IssueTracker_ASW#23]
El error que dona es:

```
TypeError in IssuesController#create

no implicit conversion of nil into String

respond_to do |format|
       if !User.exists?(id: params[:assignee_id])
           **format.json {render json: {"error":"User with id="+params[:assignee_id]+" does not exist"}, status: :unprocessable_entity}**       
       else        
           if @issue.save
                @watcher = Watcher.new

Trace:

app/controllers/issues_controller.rb:76:in `+'
app/controllers/issues_controller.rb:76:in `block (2 levels) in create'
app/controllers/issues_controller.rb:74:in `create'

Request
Parameters:

{"Title"=>"issue prova", "Status"=>"New", "Priority"=>"Trivial", "Type"=>"Bug"}

```

**Comment by AleixBalletbo** [comment]
Arreglat a https://github.com/carlotacb/IssueTracker_ASW/commit/18edf393b6a49e7d0bcea1ff9e31443fe671c635
